config/routes.rb
Rails.application.routes.draw do
  devise_for :students
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: "landings#show"

  resources :housing_applications, only: [:new, :create, :index, :show]
  resources :halls, only: [:index, :show]
  #resources :students, only: [dd

  #devise_scope :student do
  #  get "sign_in", to: "devise/sessions#new"
  #  get "sign_out", to: "devise/sessions#destroy"
  #end

  get  ':page', to: 'pages#static_page',  as: :static
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/hall.rb
class Hall < ActiveRecord::Base
  has_many :hall_housing_applications
  has_many :housing_applications, through: :hall_housing_applications

  has_attached_file :avatar, styles: { medium: "1200x500>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/


    default_scope -> { order(name: :asc) }
end

app/models/hall_housing_application.rb
class HallHousingApplication < ActiveRecord::Base
  belongs_to :housing_application
  belongs_to :hall
end

app/models/housing_application.rb
class HousingApplication < ActiveRecord::Base
  belongs_to :student
  has_and_belongs_to_many :student_classifications
  has_many :hall_housing_applications
  has_many :halls, through: :hall_housing_applications

  validates :acknowledgement, acceptance: true
  validates_uniqueness_of :stud_id, scope: :academic_year, message: "have already submitted an application for this year"

  delegate :email, to: :student, allow_nil: true
end

app/models/student.rb
class Student < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :housing_application

  #has_many :hall_assignments
  #has_many :halls, through: :hall_assignments
  
  validates :password, presence: true
  validates :st_id, presence: true
  validates(
    :email,
    presence: true,
    uniqueness: true,
    format: { with: /\A.+@claflin\.edu\z/i }
  )

  default_scope { order("email ASC") }

  before_save :downcase_data

  private

  def downcase_data
    self.email = email.downcase
  end
end

app/models/student_classification.rb
class StudentClassification < ActiveRecord::Base
  has_and_belongs_to_many :housing_applications
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.

  def not_found
    render file: "#{Rails.root}/public/404.html",  status: 404
  end
  protect_from_forgery with: :exception
end

app/controllers/halls_controller.rb
class HallsController < ApplicationController
  def index
    @halls = Hall.all
  end

  def show
    @hall = Hall.find(params[:id])
  end
end

app/controllers/housing_applications_controller.rb
class HousingApplicationsController < ApplicationController
  before_action :authenticate_student!

  def index
    @applications = HousingApplication.all
  end

  def new
    @application = HousingApplication.new
    @application.stud_id = current_student.st_id

    check_for_preferred_roommates
  end

  def create
    @application = HousingApplication.new(housing_application_params)

    if @application.save
      flash[:notice] = "Application submitted successfully"
      redirect_to root_path
    else
      flash.now[:alert] = "Application cannot be submitted"
      render :new
    end
  end

  private

  def check_for_preferred_roommates
    @applications = HousingApplication.all
    rm = []
    @applications.each do |app|
      if ((app.roommate1 or app.roommate2 or app.roommate3).eql?(current_student.st_id))
        rm << app.student.st_id
      end
    end

    @application.roommate1 = rm[0]
    @application.roommate2 = rm[1]
    @application.roommate3 = rm[2]
  end

  def housing_application_params
    params.
      require(:housing_application).
      permit(:academic_year, :semester, :home_address, :home_phone, :stud_id, :gender, :parent_name, :parent_address, :parent_home_telephone, :parent_work_telephone, :room1, :room2, :room3, :roommate_preference, :roommate1, :roommate2, :roommate3, :any_disability, :disability_description, :previous_application, :acknowledgement, student_classification_ids: []).  #, hall_ids: []).
      merge(student: current_student)
  end
end

app/controllers/landings_controller.rb
class LandingsController < ApplicationController
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # skip_before_filter :require_login
  def static_page
    return not_found unless Dir.glob(Rails.root.join('app', 'views', 'pages', params[:page]).to_s + '.*').present?

    send(params[:page]) if self.respond_to?(params[:page])
    render template: "pages/#{params[:page]}"
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/halls_helper.rb
module HallsHelper
end

app/helpers/housing_applications_helper.rb
module HousingApplicationsHelper
end

app/helpers/landings_helper.rb
module LandingsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/application/_alert.html.erb
<% if current_page?(root_path) %>
	<p class="notice"><%= notice %></p>
	<p class="alert"><%= alert %></p>
<% elsif current_page?('/housing_applications/new') -%>
	<ul>
	  <% if flash.now[:alert] or flash[:notice] %>
	    <% flash.each do |name, msg| -%>
	      <li><%= content_tag :div, msg, class: name %></li>
	    <% end -%>
	    	
	  <% end %>

	  <% if !(@application.errors.empty?) %>
	    <% @application.errors.full_messages.each do |error_message| %>
		    <% if error_message.include?("Stud") %>
			    <% error_message.gsub!("Stud", "You") %>
			<% end -%>
		      <li><p class="alert"><%= error_message %></p></li>
	    <% end %>
	  <% end %>
	</ul> 
<% end -%>

app/views/application/_footer.html.erb
<!-- Footer start -->
<div id="wrapper">
	<div id="footer">
      		<!-- <div class="col col-sm-12"> -->
              <!-- <div class="panel"> -->
                  © 2015 Ifeanyi Kalu, All Rights Reserved.
              <!-- </div> -->
      	    <!-- </div>  -->
  	</div> <!-- .row -->
</div><!-- .container -->

app/views/application/_header_for_body.html.erb
<header class="masthead">
  <div class="container">
    <div class="row">
      <div class="col col-sm-6">
        <h1><a href="#" title="scroll down for your viewing pleasure">Department of Residential Life</a>
          <p class="lead">Claflin University</p></h1>
      </div>
      <div class="col col-sm-6">
        <div class="well pull-right">
          <%= image_tag ("cu.jpg") %>        
        </div>
      </div>
    </div>
  </div>
  
  <div class="container">
  <div class="row">
      <div class="col col-sm-12">
        
        <div class="panel">
        <div class="panel-body">
          The residence halls are closed for the break. Stay well and blessed.  <span class="glyphicon glyphicon-heart-empty"></span>
        </div>
        </div>
        
      </div>
    </div>
  </div>
</header>

app/views/application/_login.html.erb
<% if student_signed_in? %>
  <h5>Welcome <%= current_student.email%></h5>
  <%= link_to "Sign out", "/students/sign_out", method: :delete %>
<% else %>
  <%= link_to "Login", "/students/sign_in" %>
<% end %>

app/views/application/_navbar.html.erb
<nav class="navbar navbar-static">
    <div class="container">
      <a class="navbar-toggle" data-toggle="collapse" data-target=".nav-collapse">
        <span class="glyphicon glyphicon-chevron-down"></span>
      </a>
      <div class="nav-collapse collase">
        <ul class="nav navbar-nav"> 
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Housing</a> 
            <ul class="dropdown-menu">
              <li><%= link_to "Residence Halls", halls_path %></li>
              <li><%= link_to "Rates and Amenities", static_path('rates') %></li>
              <li class="app-link"><%= link_to "Housing Application", new_housing_application_path %></li>
              <li><%= link_to "Housing Contract", static_path('contract') %></li>
              <li><%= link_to "Housing for Current Residents", static_path('current') %></li>
              <li><%= link_to "Housing for Incoming Residents", static_path('incoming') %></li>
              <li><%= link_to "Spring Housing", static_path('spring') %></li>
              <li><%= link_to "Summer Housing", static_path('summer') %></li>
              <li class="divider"></li>
              <li><%= link_to "About", root_path %></li>
             </ul>
          </li>  
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Services & Forms</a> 
            <ul class="dropdown-menu">
              <li><%= link_to "Maintenance Requests", static_path('maintenance') %></li>
              <li><%= link_to "Room Move Requests", static_path('room_move') %></li>
              <li><%= link_to "Space Reservation", static_path('space') %></li>
              <li><%= link_to "Housing Contract", static_path('contract') %></li>
              <li><%= link_to "Housing Policy", static_path('policy') %></li>
              <li><%= link_to "Residential Life Cares", static_path('cares') %></li>
              <li><%= link_to "Artwork Submissions", static_path('artwork') %></li>
              <li class="divider"></li>
              <li><%= link_to "About", root_path %></li>
             </ul>
          </li> 
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Staff</a> 
            <ul class="dropdown-menu">
              <li><%= link_to "Full-time Staff", static_path('full_time') %></li>
              <li><%= link_to "Student Staff", static_path('student_staff') %></li>
              <li><%= link_to "Employment", halls_path %></li>
              <li><%= link_to "Staff Resources", halls_path %></li>
              <li class="divider"></li>
              <li><%= link_to "Contact Us", root_path %></li>
             </ul>
          </li> 
          <li><a href="#">Contact Us</a></li>
        </ul>
        <ul class="nav navbar-right navbar-nav">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="glyphicon glyphicon-search"></i></a>
            <ul class="dropdown-menu" style="padding:12px;">
                <form class="form-inline">
            <button type="submit" class="btn btn-default pull-right"><i class="glyphicon glyphicon-search"></i></button><input type="text" class="form-control pull-left" placeholder="Search">
                </form>
              </ul>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="glyphicon glyphicon-user"></i> <i class="glyphicon glyphicon-chevron-down"></i></a> 
            <ul class="dropdown-menu">
              <li><%= render "login" %></li>
              <!--<li><a href="students/sign_in">Login</a></li>-->
              <!--<li><a href="#">Profile</a></li>-->
              <% if student_signed_in? %>
              <li class="divider"></li>
              <li><a href="#">Profile</a></li>
            <% end %>
             </ul>
          </li>  
        </ul>
      </div>    
    </div>
</nav><!-- /.navbar -->

app/views/application/_new_hall_application.html.erb
<div class="container">
  <div class="row">
    <div class="col col-sm-12">
      <div class="panel">
        <h1> STUDENT HOUSING APPLICATION </h1>
        <%= form_for @application do |form| %>
          <div>
            <div>
              Academic year: <%= form.select :academic_year, 
                (2010..Time.now.year).map { |year| "#{year} / #{year + 1}" }, prompt: "Select Academic Year" %>
                <sp class="tab">Choose one:</sp> 
                <st class="space"><%= form.radio_button :semester, "Fall", checked: true %>Fall <%= form.radio_button :semester, "Spring" %>Spring <%= form.radio_button :semester, "Summer" %>Summer</st>
              </div><br/>

              <div>
                Home address: <%= form.text_field :home_address, placeholder: "City\t\tState\tZip code", size: "100" %>
              </div><br/>
              <div>
                Home phone: <%= form.text_field :home_phone, placeholder: "1 (XXX)-XXX-XXXX" %>
                <sp class="tab2">Student ID: <%= form.text_field :stud_id %></sp>
                <sp class="tab2">Gender: <sp class="space"><%= form.radio_button :gender, "Male", checked: true %>Male <%= form.radio_button :gender, "Female" %>Female</sp></sp>
              </div><br/>

              <!--
              Age:  form.text_field :age 
              Date of birth: %= form.date_select :date_of_birth, 
                start_year: 1900, end_year: Time.now.year, 
                order: [:year, :month, :day], 
                prompt: {year: "Choose year", month: "Choose month", day: "Choose day"} %>
                -->

                <div>
                  Parent/Guardian name: <%= form.text_field :parent_name, size: "100" %>
                </div><br/>
                <div>
                  Parent/Guardian address: <%= form.text_field :parent_address, placeholder: "City\t\tState\tZip code", size: "100" %>
                </div><br/>
                <div>
                  Parent/Guardian home phone: <%= form.text_field :parent_home_telephone, placeholder: "1 (XXX)-XXX-XXXX" %>
                  <sp class="tab2">Parent/Guardian work phone: <%= form.text_field :parent_work_telephone, placeholder: "1 (XXX)-XXX-XXXX" %></sp>
                </div><br/>
                <div>
                  Student's current status at Claflin: <%= form.collection_check_boxes(:student_classification_ids, StudentClassification.all, :id, :classification) do |b| %>
                    <%= b.label(class: "status-tab3") {b.check_box + b.text} %> 
                  <% end %>
                </div>
              </div>

              <h1> PART 2: BUILDING PREFERENCE </h1>
              <i> (Please indicate your choice of residence hall in order preference) </i>
              
             <!--  <div>
                <%= form.collection_check_boxes(:hall_ids, Hall.all, :id, :name) do |b| %>
                  <%= b.label(class: "halls-tab3", :"data-value" => b.value) {b.check_box + b.text} %>
                  <%= select_tag 'hall_ids', options_for_select(["1", "2", "3"].map {|rate| "#{rate}" }), include_blank: true %>
                <% end %>
              </div> -->

              <div class="halls">
                <p>
                  <%= form.collection_select :room1, Hall.all, :name, :name, prompt: "Please select your most preferred hall" %>
                </p>
                 <p>
                  <%= form.collection_select :room2, Hall.all, :name, :name, prompt: "Please select your more preferred hall" %>
                </p>
                 <p>
                  <%= form.collection_select :room3, Hall.all, :name, :name, prompt: "Please select your preferred hall" %>
                </p>
                
              </div>



              <h1> PART 3: ROOMMATE PREFERENCE </h1>
              <i> (Please indicate roommate preference) </i>
              <div>
                <p>A. Do you have roommate preferences? <%= form.check_box :roommate_preference %> <br />
                  My choice of roommate/ suite mates is indicated below <span> <i>(Preferred roommates must submit applications to the Office of Residential Life at the same time. Please be advised that roommate requests can only be honored if space is available and paid at the same time) </i> </span></p>
                ROOMMATE'S STUDENT ID: <%= form.text_field :roommate1, placeholder: " ID Number", size: "50" %><br /><br/>
                ROOMMATE'S STUDENT ID: <%= form.text_field :roommate2, placeholder: " ID Number", size: "50" %><br /><br/>
                ROOMMATE'S STUDENT ID: <%= form.text_field :roommate3, placeholder: " ID Number", size: "50" %>
              </div>
              <h1> PART 4: OTHER INFORMATION </h1>
              <div>
                <p>A. Do you have a disability that requires special accommodation? <%= form.check_box :any_disability %><br/>
                  If yes, please attach information about your disability including verification from your personal physician. <%= form.text_area :disability_description, size: "100x10" %> </p>
                B. Have you previously applied for housing at Claflin University? <%= form.check_box :previous_application%>
              </div>

              <h1> PART 5: REQUIRED ACKNOWLEDGEMENT </h1>
              <p><i>I understand that by signing below that it is expected that I reside in Claflin University housing for the entire academic year. I understand my preferences for residence halls and roommate will be honored if possible, but cannot be guaranteed. By signing below, I agree to respect and adhere to all policies and procedures of the Office of Residential Life and the Claflin University Student Code of Conduct.</i></p>
              <sp class="tab1"><%= form.check_box :acknowledgement %>I acknowledge.</sp>

              <%= form.submit "Submit" %>
            <% end %>
          </div>
        </div> 
      </div><!-- .row -->
    </div><!-- .container -->

app/views/application/_side_nav.html.erb
<div class="col col-sm-3">
  <div id="sidebar">
    <ul class="nav nav-stacked">
      <li><h3 class="highlight">Channels <i class="glyphicon glyphicon-dashboard pull-right"></i></h3></li>
      <li><a href="#">Link</a></li>
    	<li><a href="#">Link</a></li>
    </ul>
    <div class="accordion" id="accordion2">
        <div class="accordion-group">
          <div class="accordion-heading">
            <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseOne">
                Quick Menu
            </a>
          </div>
          <div id="collapseOne" class="accordion-body collapse in">
            <div class="accordion-inner">
              <p>There is a lot to be said about RWD.</p>
            </div>
          </div>
        </div>
        <div class="accordion-group">
            <div class="accordion-heading">
                <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseTwo">
                    Calendar
                </a>
            </div>
            <div id="collapseTwo" class="accordion-body collapse">
                <div class="accordion-inner">
                  <p>Use @media queries or utility classes to customize responsiveness.</p>
                </div>
            </div>
        </div>
    </div>
  </div>
</div> 

app/views/halls/index.html.erb
<%= render "header_for_body" %> 

<!-- Begin Body -->
<div class="container">
  <div class="row">
    <%= render "side_nav" %> 
    <div class="col col-sm-9">
      <div class="panel">
        <h1>Residence Halls</h1>
        <ul>
          <% @halls.each do |hall| %>
            <hr>
            <li><%= link_to hall.name, hall %></li>
          <% end %>
        </ul>
      </div>
    </div> 
  </div>
</div>

app/views/halls/show.html.erb
<div id="hall-detail">
  <div class="hall">

    <table>
      <tr>
        <th> <%= @hall.name %> </th>
      </tr>
      <tr>
        <td><%= image_tag @hall.avatar.url(:medium) %></td>
        <td> <%= @hall.info %> </td>
      </tr>
    </table>


  </div>
</div>

app/views/housing_applications/new.html.erb
<%= render "alert" %>
<%= render "new_hall_application" %>

app/views/landings/show.html.erb
<%= render "header_for_body" %> 
<!-- Begin Body -->
<div class="container">
  <div class="row">
    <%= render "side_nav" %> 
    <div class="col col-sm-9">
      <div class="panel">
        <h1>Panther Plaza</h1>

        <div class="row">
          <div class="col col-sm-12">
            <%= image_tag ("halls/plaza1.JPG"), :class => "img-responsive" %> 
          </div> 
          <!-- <div class="col col-sm-4">
            <%= image_tag ("cu3.jpg"), :class => "img-responsive" %> 
            <h4>Aside</h4>
            <hr>
            <%= image_tag ("cu2.jpg"), :class => "img-responsive" %> 
            <h4>Aside 2</h4>
          </div>    -->
        </div>

        <h2>Content</h2>
        Totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae 
        dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia cor magni dolores 
        eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, 
        sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. 
        Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur?


        <h2>Content</h2>
        Rrem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae 
        dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia cor magni dolores 
        eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, 
        sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. 
        Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut
        <br><br>
        <button class="btn btn-default">More</button>

        <hr>

       <!--  <h2>Content</h2>
        <img src="//placehold.it/150x100/EEEEEE" class="img-responsive pull-right"> Farmhand ida quae ab illo inventore veritatis et quasi architecto beatae vitae 
        dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia cor magni dolores 
        eos qui ratione voluptatem sequi nesciunt. I met him on the Internet. He's a French model. Qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, 
        sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. 
        Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut
        <br><br>
        <button class="btn btn-default">More</button>

        <hr>

        <div class="row">
          <div class="col col-sm-6">
            <img src="/assets/example/bg_smartphones.jpg" class="img-responsive">

          </div> 
          <div class="col col-sm-6">
            <h1>There is still a lot to be said about the Responsive Web.</h1>
          </div>   
        </div>

        <hr>

        <h2>Responsive Text</h2>
        Eeaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae 
        dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia cor magni dolores 
        eos qui ratione voluptatem sequi nesciunt. Bootply is this awesomeness. Editor, prototype tool, adipisci velit, 
        sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. 
        Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut

        <hr>

        <h2>Responsive Images</h2>
        Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, 
        totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae 
        dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia cor magni dolores 
        eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, 
        sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. 
        Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut

        <hr>

        <h2>Media Queries</h2>
        Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, 
        totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae 
        dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia cor magni dolores 
        eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, 
        sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. 
        Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut -->


        <h1><a hre 
            <hr>

            <!-- <h2>Media Queries</h2> -->
            Have a pleasant experience in our halls!
            <!-- We wish your experience in the resident halls to be pleasant! -->
            <hr>
          </div>
        </div> 
      </div>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Residential Life | Claflin University</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= render "navbar" %> 
    <!-- <p class="notice"><%= notice %></p> -->
   <!--  <p class="alert"><%= alert %></p> -->
   
   <%= render "alert" %>
 
    <%= yield %>

    <%= render "footer" %> 

  </body>
</html>

app/views/pages/claflin_commons.html.erb
<div id="staff-list">
  <div class="pics">
    <div class="c-staff">
      <st class="haigler">
      <%= image_tag("staff/avatar3.jpg", size: '250x230') %>
      </st>
      <st class="leroy">
      <%= image_tag("staff/leroy-durant.jpg", size: '400x350')%>
      </st>
      <span class="devin">
        <%= image_tag("staff/devin-randolph.jpg", size: '300x330') %>
      </span>
    </div>
  </div>
</div>

app/views/pages/full_time.html.erb
<div id="staff-list">
  <div class="pics">
    <div class="c-staff">
      <st class="haigler">
      <%= image_tag("staff/avatar3.jpg", size: '250x230') %>
      </st>
      <st class="leroy">
      <%= image_tag("staff/leroy-durant.jpg", size: '400x350')%>
      </st>
      <span class="devin">
        <%= image_tag("staff/devin-randolph.jpg", size: '300x330') %>
      </span>
    </div>
  </div>
</div>

app/views/students/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<!--
<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>
-->

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>